GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ODg1ZmQ3MmRmZGNjNjExYTM5YjgwIiwiaWF0IjoxNjg0NTc3NTY1fQ.ZfmWtOh05GVlkzCgbllB1HlqLyb5MKUrDrEzUryXooM


###############################
//// REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thuan",
    "password": "thuandeptrai"
}


######################################################
/// LOGIN IN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thuan",
    "password": "thuandeptrai"
}

########################################################
/// CREATE COLLECTION
POST http://localhost:5000/api/collections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc

{
    "name": "Groceries",
    "image": "shopping",
    "color": "#CFB452",
    "tasks": []
}

########################################################
/// GET all Collections
GET http://localhost:5000/api/collections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc



########################################################
/// Add task to COLLECTION
POST http://localhost:5000/api/collections/64e624bf90f6b52758f0a8d5/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI5NjY0fQ.4v1by5XWJ5tpICXgb7xlWI28N2uLPJsgo10qZ6GkJdA

{
    "name": "TEST 2",
    "note": "",
    "check": true
}

########################################################
/// GET One Collections
GET http://localhost:5000/api/collections/64e624bf90f6b52758f0a8d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc


########################################################
/// Update TASK
PUT http://localhost:5000/api/collections/64cbd43f99f76b706e823121/tasks/64cbdadd99f76b706e823153
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc

{
    "check": true
}

########################################################
/// Delete TASK
DELETE http://localhost:5000/api/collections/64e6251990f6b52758f0a8e2/tasks/64eb14fadce06c13609bf88b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc


########################################################
/// Delete all tasks in one collection
DELETE http://localhost:5000/api/collections/64e624bf90f6b52758f0a8d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ2ZjcwOTcxOTdlMjc5ODQ2YTgwZGU3IiwiaWF0IjoxNjg1MDI0OTIyfQ.80a2A-m9fTgHRge3N5AHCnmHa_SrOSqo_pUyV6HNKYc
