export const API_URL = "http://localhost:5000/api";

export const LOCAL_STORAGE_TOKEN_NAME = "to-do-list";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const COLLECTION_VIEW = "collection_view";
export const COLLECTIONS_LOADED_SUCCESS = "COLLECTIONS_LOADED_SUCCESS";
export const COLLECTION_VIEW_LOADED_SUCCESS = "COLLECTION_VIEW_LOADED_SUCCESS";
export const COLLECTIONS_ADD_SUCCESS = "COLLECTIONS_ADD_SUCCESS";
export const COLLECTION_VIEW_RESET = "COLLECTION_VIEW_RESET";

export const TASKS_LOADED_SUCCESS = "TASKS_LOADED_SUCCESS";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
